### ISSUE TITLE
Error window caused by Dull Spined Clam

### ISSUE THREAD

**Issue by antarek** [dapal-003/Openables-be-gone#1]
Addon version: 1.28
Client version: 10.0.2 (french language)

Error: ![image](https://user-images.githubusercontent.com/42368527/213872062-ca12a4dc-f1d3-41fd-9da2-46d28afb990d.png)

This pop-up appears for as long as you have any Dull Spined Clam inside of your inventory and haven't yet disabled them from the list of items to open using the addon check list.

**Comment by dapal-003** [comment]
I've removed them from the list as they're not able to be opened by lua code sadly
